version: '3.8'

services:
  postgres:
    container_name: cours_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-courspringbootdb}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: cours_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - postgres
    restart: unless-stopped

  springboot_app:
    container_name: cours_java_springboot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8098:8080"
    networks:
      - postgres  # Connect to the same network as PostgreSQL if needed

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: